chain_config: /home/ubuntu/validator/akhira/genesis.json
secrets_config: ""
data_dir: ./data-dir
block_gas_target: "0x0"
grpc_addr: 0.0.0.0:9632
jsonrpc_addr: 0.0.0.0:20003
telemetry:
    prometheus_addr: ""
network:
    no_discover: false
    libp2p_addr: 127.0.0.1:1998
    nat_addr: 35.178.166.53
    dns_addr: ""
    max_peers: -1
    max_outbound_peers: -1
    max_inbound_peers: -1
seal: true
tx_pool:
    price_limit: 0
    max_slots: 4096
log_level: INFO
restore_file: ""
block_time_s: 2
headers:
    access_control_allow_origins:
        - '*'
log_to: ""

